/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author kimbe
 */
public class Calculadora extends javax.swing.JFrame {

    
    String valor1;
    String signo;
    String valor2;
    
    /**
     * Creates new form Calculadora
     */
    public Calculadora() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

  
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        btnborrartodo = new javax.swing.JRadioButton();
        btnborrar = new javax.swing.JRadioButton();
        btndividir = new javax.swing.JRadioButton();
        jbtnmultiplicar = new javax.swing.JRadioButton();
        btnrestar = new javax.swing.JRadioButton();
        btnsumar = new javax.swing.JRadioButton();
        btnpunto = new javax.swing.JRadioButton();
        btnigual = new javax.swing.JRadioButton();
        jButon7 = new javax.swing.JButton();
        jButon8 = new javax.swing.JButton();
        jButon9 = new javax.swing.JButton();
        jButon4 = new javax.swing.JButton();
        jButon5 = new javax.swing.JButton();
        jButon6 = new javax.swing.JButton();
        jButon1 = new javax.swing.JButton();
        jButon2 = new javax.swing.JButton();
        jButon3 = new javax.swing.JButton();
        jButon0 = new javax.swing.JButton();
        txtmostrar = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        buttonGroup1.add(btnborrartodo);
        btnborrartodo.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnborrartodo.setText("CE");
        btnborrartodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrartodoActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrartodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, 50, 50));

        buttonGroup1.add(btnborrar);
        btnborrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnborrar.setText("C");
        btnborrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnborrarActionPerformed(evt);
            }
        });
        jPanel1.add(btnborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 130, 50, 50));

        buttonGroup1.add(btndividir);
        btndividir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btndividir.setText("/");
        btndividir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndividirActionPerformed(evt);
            }
        });
        jPanel1.add(btndividir, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 130, 50, 50));

        buttonGroup1.add(jbtnmultiplicar);
        jbtnmultiplicar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbtnmultiplicar.setText("*");
        jbtnmultiplicar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnmultiplicarActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnmultiplicar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 130, 50, 50));

        buttonGroup1.add(btnrestar);
        btnrestar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnrestar.setText("-");
        btnrestar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrestarActionPerformed(evt);
            }
        });
        jPanel1.add(btnrestar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 200, 50, 50));

        buttonGroup1.add(btnsumar);
        btnsumar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        btnsumar.setText("+");
        btnsumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsumarActionPerformed(evt);
            }
        });
        jPanel1.add(btnsumar, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 270, 50, 100));

        buttonGroup1.add(btnpunto);
        btnpunto.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnpunto.setText(".");
        btnpunto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnpuntoActionPerformed(evt);
            }
        });
        jPanel1.add(btnpunto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 390, 50, 40));

        buttonGroup1.add(btnigual);
        btnigual.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        btnigual.setText("            =");
        btnigual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnigualActionPerformed(evt);
            }
        });
        jPanel1.add(btnigual, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, 160, 40));

        jButon7.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon7.setText("7");
        jButon7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon7, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 50, 40));

        jButon8.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon8.setText("8");
        jButon8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon8, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 50, 40));

        jButon9.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon9.setText("9");
        jButon9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon9ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon9, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 50, 40));

        jButon4.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon4.setText("4");
        jButon4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon4, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 270, 50, 40));

        jButon5.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon5.setText("5");
        jButon5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon5, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 50, 40));

        jButon6.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon6.setText("6");
        jButon6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 50, 40));

        jButon1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon1.setText("1");
        jButon1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 50, 40));

        jButon2.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon2.setText("2");
        jButon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 330, 50, 40));

        jButon3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon3.setText("3");
        jButon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 330, 50, 40));

        jButon0.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jButon0.setText("0");
        jButon0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButon0ActionPerformed(evt);
            }
        });
        jPanel1.add(jButon0, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 390, 50, 40));

        txtmostrar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jPanel1.add(txtmostrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 340, 60));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/fondo (2).jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 590, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButon5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon5ActionPerformed
       
//        a="5";
//        lista.add(a);
//       texto.setText(a);
        txtmostrar.setText(txtmostrar.getText()+"5");

    }//GEN-LAST:event_jButon5ActionPerformed

    private void jButon1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon1ActionPerformed
        
        txtmostrar.setText(txtmostrar.getText()+"1");
    }//GEN-LAST:event_jButon1ActionPerformed

    private void jButon7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon7ActionPerformed
       
       txtmostrar.setText(txtmostrar.getText()+"7");
    }//GEN-LAST:event_jButon7ActionPerformed

    private void jButon8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon8ActionPerformed
       
        txtmostrar.setText(txtmostrar.getText()+"8");
        
    }//GEN-LAST:event_jButon8ActionPerformed

    private void jButon9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon9ActionPerformed
        
        txtmostrar.setText(txtmostrar.getText()+"9");
    }//GEN-LAST:event_jButon9ActionPerformed

    private void jButon4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon4ActionPerformed
       
        txtmostrar.setText(txtmostrar.getText()+"4");
    }//GEN-LAST:event_jButon4ActionPerformed

    private void jButon6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon6ActionPerformed
        
        txtmostrar.setText(txtmostrar.getText()+"6");
    }//GEN-LAST:event_jButon6ActionPerformed

    private void jButon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon2ActionPerformed
        
        txtmostrar.setText(txtmostrar.getText()+"2");
    }//GEN-LAST:event_jButon2ActionPerformed

    private void jButon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon3ActionPerformed
      
        txtmostrar.setText(txtmostrar.getText()+"3");
    }//GEN-LAST:event_jButon3ActionPerformed

    private void jButon0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButon0ActionPerformed
        
       txtmostrar.setText(txtmostrar.getText()+"0");
    }//GEN-LAST:event_jButon0ActionPerformed

    private void btnpuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnpuntoActionPerformed
        
        String cadena;
        cadena=txtmostrar.getText();
        
        if (cadena.length()<=0) {
            txtmostrar.setText("0.");
          }
        else{
            if (!punto(txtmostrar.getText())) {
                txtmostrar.setText(txtmostrar.getText()+".");               
            }  
        }
    }//GEN-LAST:event_btnpuntoActionPerformed

    private void btnborrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrarActionPerformed
        //creo una variable llamada cadena
        String cadena;
        //cadena la igualo al texto del jtextfield
        cadena=txtmostrar.getText();
        if (cadena.length()>0) {
            cadena=cadena.substring(0, cadena.length()-1);
            txtmostrar.setText(cadena);
        }   
    }//GEN-LAST:event_btnborrarActionPerformed

    private void btnborrartodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnborrartodoActionPerformed
        
        //borro todo el texto
        txtmostrar.setText("");
        
    }//GEN-LAST:event_btnborrartodoActionPerformed

    private void btnigualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnigualActionPerformed
        //creo variable resultado
        String resultado;
        valor2=txtmostrar.getText();
        if (!valor2.equals("")) {
            resultado=calculadora(valor1,valor2,signo);
            txtmostrar.setText(resultado);
        }
        
    }//GEN-LAST:event_btnigualActionPerformed

    private void btndividirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndividirActionPerformed
        
        if (!txtmostrar.getText().equals("")) {
            valor1=txtmostrar.getText();
            signo="/";
            txtmostrar.setText("");
        }
            
    }//GEN-LAST:event_btndividirActionPerformed

    private void btnsumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsumarActionPerformed
       
        if (!txtmostrar.getText().equals("")) {
            valor1=txtmostrar.getText();
            signo="+";
            txtmostrar.setText("");
        }
        
    }//GEN-LAST:event_btnsumarActionPerformed

    private void btnrestarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrestarActionPerformed
      
        if (!txtmostrar.getText().equals("")) {
            valor1=txtmostrar.getText();
            signo="-";
            txtmostrar.setText("");
        }
        
    }//GEN-LAST:event_btnrestarActionPerformed

    private void jbtnmultiplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnmultiplicarActionPerformed
    
        if (!txtmostrar.getText().equals("")) {
            valor1=txtmostrar.getText();
            signo="*";
            txtmostrar.setText("");
        }
        
    }//GEN-LAST:event_jbtnmultiplicarActionPerformed

    public static String calculadora(String valor1,String valor2,String signo){
    Double resultado=0.0;
    String respuesta;
    
    
    if (signo.equals("-")) {
        resultado=Double.parseDouble(valor1)-Double.parseDouble(valor2);
        
    }
    if (signo.equals("+")) {
        resultado=Double.parseDouble(valor1)+Double.parseDouble(valor2);
        
    }
    if (signo.equals("*")) {
        resultado=Double.parseDouble(valor1)*Double.parseDouble(valor2);
        
    }
    if (signo.equals("/")) {
        resultado=Double.parseDouble(valor1)/Double.parseDouble(valor2);
        
    }
    
    respuesta=resultado.toString();
    return respuesta;
}
    
    public static boolean punto(String cadena){
        boolean resultado;
        resultado=false;
        
        for (int i = 0; i < cadena.length(); i++) {
            if (cadena.substring(i, i+1).equals(".")) {
                resultado=true;
                break;
            }
        }
        return resultado;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Calculadora.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Calculadora().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton btnborrar;
    private javax.swing.JRadioButton btnborrartodo;
    private javax.swing.JRadioButton btndividir;
    private javax.swing.JRadioButton btnigual;
    private javax.swing.JRadioButton btnpunto;
    private javax.swing.JRadioButton btnrestar;
    private javax.swing.JRadioButton btnsumar;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButon0;
    private javax.swing.JButton jButon1;
    private javax.swing.JButton jButon2;
    private javax.swing.JButton jButon3;
    private javax.swing.JButton jButon4;
    private javax.swing.JButton jButon5;
    private javax.swing.JButton jButon6;
    private javax.swing.JButton jButon7;
    private javax.swing.JButton jButon8;
    private javax.swing.JButton jButon9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButton jbtnmultiplicar;
    private javax.swing.JTextField txtmostrar;
    // End of variables declaration//GEN-END:variables
}
